package org.apache.jsp.Files.JSP.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class changeimg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	} 

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function hideMessage()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"message\").style.display=\"none\"; \r\n");
      out.write("}\r\n");
      out.write("function startTimer() \r\n");
      out.write("{\r\n");
      out.write("\tvar tim = window.setTimeout(\"hideMessage()\", 5000);  // 5000 milliseconds = 5 seconds\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".nits {\r\n");
      out.write("\t-moz-box-shadow:inset 0px 0px 0px 0px #b5ccaa;\r\n");
      out.write("\t-webkit-box-shadow:inset 0px 0px 0px 0px #b5ccaa;\r\n");
      out.write("\tbox-shadow:inset 0px 0px 0px 0px #b5ccaa;\r\n");
      out.write("\tbackground-color:#a6a4eb;\r\n");
      out.write("\t-moz-border-radius:20px;\r\n");
      out.write("\t-webkit-border-radius:20px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tborder:2px solid #f5f5f5;\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tcolor:#fcfcfc;\r\n");
      out.write("\tfont-family:arial;\r\n");
      out.write("\tfont-size:17px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tpadding:8px 11px;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\ttext-shadow:1px 0px 3px #000000;\r\n");
      out.write("\tcursor:hand;\r\n");
      out.write("}.nits:hover {\r\n");
      out.write("\tbackground-color:#d46a84;\r\n");
      out.write("}.nits:active {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:1px;\r\n");
      out.write("}\r\n");
      out.write("/* This imageless css button was generated by CSSButtonGenerator.com */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

	String img=request.getParameter("name");
	System.out.println("-=-=-==-="+img);

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/ChangeImage\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"img\" value=\"");
      out.print(img );
      out.write("\"></input>\r\n");
      out.write("\t\t<input class=\"nits\" type=\"file\" name=\"file\" required=\"yes\"></input>\r\n");
      out.write("\t\t<input class=\"nits\" type=\"submit\" value=\"upload\"></input>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
