<html>
<head>
<%! 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	} 
%>
<script type="text/javascript">
function hideMessage()
{
	document.getElementById("message").style.display="none"; 
}
function startTimer() 
{
	var tim = window.setTimeout("hideMessage()", 5000);  // 5000 milliseconds = 5 seconds
}
</script>
<style type="text/css">
.nits {
	-moz-box-shadow:inset 0px 0px 0px 0px #b5ccaa;
	-webkit-box-shadow:inset 0px 0px 0px 0px #b5ccaa;
	box-shadow:inset 0px 0px 0px 0px #b5ccaa;
	background-color:#a6a4eb;
	-moz-border-radius:20px;
	-webkit-border-radius:20px;
	border-radius:20px;
	border:2px solid #f5f5f5;
	display:inline-block;
	color:#fcfcfc;
	font-family:arial;
	font-size:17px;
	font-weight:bold;
	padding:8px 11px;
	text-decoration:none;
	text-shadow:1px 0px 3px #000000;
	cursor:hand;
}.nits:hover {
	background-color:#d46a84;
}.nits:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
</head>
<%
	String img=request.getParameter("name");
	System.out.println("-=-=-==-="+img);
%>
<body>
	<form method="post" action="<%=request.getContextPath() %>/ChangeImage" enctype="multipart/form-data">
		<input type="hidden" name="img" value="<%=img %>"></input>
		<input class="nits" type="file" name="file" required="yes"></input>
		<input class="nits" type="submit" value="upload"></input>
	</form>
</body>
</html>